[build]
  publish = "."

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/data/config.json"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
